from time import sleep
from threading import Thread
videos = ["OOP Syllabus", "Constructor", "destructor", "file handling"]
# In this way we can access data generated by threads
# There are 2 identifiers which are following:
# 1. Thread Identifier : Given by process
# 2. Native Identifier : Given bt Operating System

class MyClass(Thread):
    def __init__(self):
        print("Constructo Called")
        super().__init__()
    
    def run(self):
        for vid in videos:
            print(f"{vid} started uploading...")
            sleep(3)
            print(f"{vid} Uploaded")

e1 = MyClass()
e1.start()
    
for i in range(5):
    sleep(0.5)
    print("Checking Copyrights")
    
